name: Deploy to Alpha

on:
  push:
    branches:
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
      - name: Build
        run: ./gradlew build

      - name: Assemble Release Bundle
        run: |
          ./gradlew bundleRelease
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE_64 }}
          alias: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - name: Tag Release
        run: |
          version_name=${GITHUB_REF##*/}
          echo "Tagging release with tag $version_name"
          git tag $version_name release/$version_name
          git push origin --tags
      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Alpha
        uses: r0adkll/upload-google-play@v1
        with:
          releaseName: ${GITHUB_REF##*/}
          serviceAccountJson: service_account.json
          packageName: com.premelc.tresetacounter
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: alpha
          whatsNewDirectory: whatsnew/